<a href="https://colab.research.google.com/github/qzwiz/private_dz_1/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np

#1
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)
#2
a = np.zeros((3,3))
print(a)
#3
q = np.random.randint(1, 11, size=(5, 5))
print(q)
#4
q = np.random.randint(0, 2,size=(4,4))
print('\n', q,'\n')
#5
q = np.random.randint(1, 11, size=(5))
f = np.random.randint(1, 11, size=(5))
print(q + f, q - f, q * f)
#6
q = np.random.randint(1, 100, size=(7))
f = np.random.randint(1, 100, size=(7))
dot = np.dot(q,f)
print(dot)
#7
q = np.random.randint(1, 11, size=(2, 2))
f = np.random.randint(1, 11, size=(2, 3))
dot = np.dot(q,f)
print(dot)
#8
q = np.random.randint(1, 11, size=(3, 3))
q = np.linalg.inv(q)
print(q)
#9
q = np.random.randint(0, 2,size=(4,4))
print(q.T)
#10
q = np.random.randint(0, 11,size=(3,4))
s = np.random.randint(0, 11,size=(4))
dot = np.dot(q,s)
print(dot)
#11
q = np.random.randint(0, 2,size=(2,3))
f = np.random.randint(0, 2,size=(3))
dot = np.dot(q,f)
print(dot)
#12
q = np.random.randint(0, 11,size=(2,2))
s = np.random.randint(0, 11,size=(2,2))
f = q*s
print("\n",f)
#13
q = np.random.randint(0, 11,size=(2,2))
s = np.random.randint(0, 11,size=(2,2))
dot = np.dot(q,s)
print(dot)
#14
q = np.random.randint(0, 101,size=(5,5))
q = np.sum(q)
print(q)
#15
q = np.random.randint(0, 11,size=(4,4))
s = np.random.randint(0, 11,size=(4,4))
s[s == 0] = 1
print(q/s)
#16
f = np.random.rand(3, 3)
s = np.sum(f, axis=1, keepdims=True)
print(s)
#17
f = np.random.randint(1, 11, size=(3, 4))
t = np.square(f)
print(t)
#18
f = np.random.randint(1, 51, size=4)
f = np.sqrt(f)
print(f)


[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 7  8 10  8  5]
 [10  9  2 10  8]
 [ 7  5  2  4  2]
 [ 5  6 10  2  8]
 [ 3  4  9  4  5]]

 [[1 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [0 0 1 0]] 

[ 5 19 11  8 14] [-1  1 -9 -4 -2] [ 6 90 10 12 48]
18203
[[ 82  58  65]
 [114  84 133]]
[[-0.24691358  0.16049383  0.2345679 ]
 [ 0.13580247  0.0617284  -0.17901235]
 [ 0.32098765 -0.30864198 -0.10493827]]
[[0 0 0 1]
 [1 1 1 1]
 [1 0 1 0]
 [0 1 0 0]]
[84 61 32]
[1 1]

 [[12 36]
 [80 48]]
[[ 56  40]
 [110 120]]
1480
[[1.5        0.16666667 0.33333333 0.        ]
 [0.625      1.33333333 1.125      1.4       ]
 [0.         2.33333333 1.25       0.33333333]
 [0.4        0.6        0.42857143 0.71428571]]
[[2.23964918]
 [1.55372552]
 [1.23722461]]
[[  4   9  25  81]
 [ 25 100   4   9]
 [ 81  16  81   9]]
[6.244998   3.60555128 4.35889894 4.89897949]
